import { Product } from './types';

export const CURATED_HERITAGE_PRODUCTS: Product[] = [
  // 1. Featured on Home: Terracotta Blue Glaze Bowl
  {
    id: '1',
    artisanId: 'a1',
    artisanName: 'Rajesh Kumar Prajapati',
    productName: 'Terracotta Blue Glaze Bowl',
    description: 'A masterpiece of traditional Khurja pottery featuring a deep celestial blue reactive glaze over hand-thrown terracotta clay.',
    craftType: 'Pottery',
    craftStyle: 'Khurja Studio Ceramic & Reactive Glaze',
    region: 'Khurja, Uttar Pradesh',
    materials: 'Natural River Clay, Mineral Cobalt Glaze, Quartz Sand',
    price: 1200,
    availableQuantity: 5,
    priceRange: {
      min: 1000,
      max: 1500,
      reasoning: 'Double kiln-fired at 1200°C for exceptional durability and food-safe vibrant glaze finish.',
    },
    images: [
      '/home-page/terracotta-bowl.jpeg',
      '/crafts/jaipur-blue-pottery.jpg',
    ],
    story: 'Hand-shaped on a traditional kick wheel by master potters of Khurja, renowned as the Ceramic City of India for over six centuries.',
    culturalNote: 'Each bowl features unique crystalline glaze patterns formed during high-temperature reduction firing.',
    tags: ['pottery', 'khurja', 'terracotta', 'ceramics', 'handmade'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 2. Featured on Home: Chanderi Silk Stole
  {
    id: '2',
    artisanId: 'a2',
    artisanName: 'Amina Begum & Weavers',
    productName: 'Chanderi Silk Stole',
    description: 'Feather-light sheer Chanderi silk stole hand-woven with fine pure zari geometric border and gossamer texture.',
    craftType: 'Textiles',
    craftStyle: 'Chanderi Handloom Weave',
    region: 'Chanderi, Madhya Pradesh',
    materials: 'Pure Mulberry Silk, Fine Cotton Yarn, Metallic Zari',
    price: 2500,
    availableQuantity: 3,
    priceRange: {
      min: 2200,
      max: 3000,
      reasoning: 'Hand-woven on traditional pit looms requiring high count silk warp and delicate gold zari weft.',
    },
    images: [
      '/home-page/chanderi-silk-stole.jpeg',
      '/crafts/kanjeevaram-saree.jpg',
    ],
    story: 'Woven by generational weavers in the historic fortress town of Chanderi, celebrated since the Vedic era for royalty-grade handlooms.',
    culturalNote: 'Chanderi fabric is renowned for its sheer transparency and lustrous drape.',
    tags: ['silk', 'scarf', 'chanderi', 'handloom', 'textiles'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 3. Featured on Home: Handpainted Madhubani Tray
  {
    id: '3',
    artisanId: 'a3',
    artisanName: 'Sunita Devi',
    productName: 'Handpainted Madhubani Tray',
    description: 'Solid mango-wood serving tray hand-painted with intricate Madhubani folklore motifs using natural botanical pigments and fine nib pens.',
    craftType: 'Hand painting',
    craftStyle: 'Kachni & Bharni Mithila Art',
    region: 'Mithila, Bihar',
    materials: 'Seasoned Mango Wood, Natural Herbal Pigments, Waterproof Protective Lacquer',
    price: 1800,
    availableQuantity: 8,
    priceRange: {
      min: 1600,
      max: 2200,
      reasoning: 'Over 16 hours of intricate line-work depicting nature harmony and auspicious wedding motifs.',
    },
    images: [
      '/home-page/handpainted-madhubani-tray.jpeg',
    ],
    story: 'Each stroke is hand-drawn without stencils, passing sacred Mithila painting traditions from mother to daughter across millennia.',
    culturalNote: 'The double-line borders and floral hatchings are the signature mark of GI-tagged Mithila painting.',
    tags: ['art', 'madhubani', 'painting', 'woodwork', 'mithila'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 4. Sample Preset: Jaipur Blue Pottery
  {
    id: 'jaipur-blue-pottery',
    artisanId: 'artisan-ramesh-kumar',
    artisanName: 'Ramesh Kumar Kumhar',
    productName: 'Jaipur Blue Pottery Royal Urn',
    description: 'Authentic GI-tagged Jaipur Blue Pottery handcrafted using quartz stone powder, raw glass, and natural cobalt oxide pigments without clay.',
    craftType: 'Pottery',
    craftStyle: 'Mughal & Persian Floral Glaze',
    region: 'Jaipur, Rajasthan',
    materials: 'Quartz Stone, Multani Mitti, Natural Cobalt Oxide, Raw Glass Glaze',
    price: 3200,
    availableQuantity: 4,
    priceRange: {
      min: 3000,
      max: 3800,
      reasoning: 'Intricate double-firing process and hand-painted Persian cobalt floral patterns.',
    },
    images: [
      '/crafts/jaipur-blue-pottery.jpg',
    ],
    story: 'Carrying forward a 5-generation legacy of palace potters from the royal ateliers of Maharaja Sawai Ram Singh II.',
    culturalNote: 'One of the few pottery crafts globally that uses quartz instead of clay, producing a glassy turquoise resonance.',
    tags: ['BluePottery', 'JaipurCraft', 'Rajasthan', 'HandmadeIndia'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 5. Sample Preset: Bastar Dhokra Art
  {
    id: 'bastar-dhokra-art',
    artisanId: 'artisan-sukhranjan-baghel',
    artisanName: 'Sukhranjan Baghel',
    productName: 'Bastar Tribal Dhokra Musician Figurine',
    description: '4,000-year-old non-ferrous bell metal casting technique using beeswax threads and riverbed clay molds from Bastar.',
    craftType: 'Metalwork',
    craftStyle: 'Bastar Lost-Wax Cast Metal',
    region: 'Bastar, Chhattisgarh',
    materials: 'Pure Bell Metal Brass, Natural Beeswax, Damar Resin, River Clay',
    price: 4800,
    availableQuantity: 3,
    priceRange: {
      min: 4500,
      max: 5600,
      reasoning: 'Single-mold lost-wax process where every piece is an irreproducible one-of-a-kind original.',
    },
    images: [
      '/crafts/bastar-dhokra-art.jpg',
    ],
    story: 'Preserved by the tribal metalsmiths of Bastar, dating back directly to the prehistoric Dancing Girl artifact of Mohenjo-Daro.',
    culturalNote: 'Because the wax mold is destroyed during molten pouring, no two Dhokra statues can ever be identical.',
    tags: ['DhokraArt', 'LostWaxCasting', 'TribalHeritage', 'BastarBrass'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 6. Sample Preset: Kanjeevaram Saree
  {
    id: 'kanjeevaram-saree',
    artisanId: 'artisan-murugan',
    artisanName: 'Murugan Thari',
    productName: 'Kanjeevaram Pure Silk Korvai Saree',
    description: 'Legendary temple handloom saree crafted from 3-ply twisted mulberry silk with solid gold zari Korvai interlocking borders.',
    craftType: 'Textiles',
    craftStyle: 'Korvai Interlocking Handloom',
    region: 'Kanchipuram, Tamil Nadu',
    materials: 'Pure Mulberry Silk (Murukku Pattu), 24K Gold Plated Silver Zari',
    price: 14500,
    availableQuantity: 2,
    priceRange: {
      min: 13000,
      max: 18000,
      reasoning: 'Woven with two weavers operating the shuttle simultaneously to interlock contrasting body and border.',
    },
    images: [
      '/crafts/kanjeevaram-saree.jpg',
    ],
    story: 'Woven in the temple city of Kanchipuram by hereditary master weavers descended from Sage Markanda.',
    culturalNote: 'The Korvai technique creates completely seamless transitions between bright borders and pallu.',
    tags: ['Kanjeevaram', 'SilkSaree', 'Handloom', 'TamilNadu'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 7. Sample Preset: Chikankari Dupatta
  {
    id: 'chikankari-dupatta',
    artisanId: 'artisan-shabana-begum',
    artisanName: 'Shabana Begum',
    productName: 'Lucknow Chikankari Shadow-Work Dupatta',
    description: 'Delicate hand-embroidered pure mulmul cotton dupatta featuring intricate Bakhiya shadow work, Phanda knots, and floral Jaal.',
    craftType: 'Textiles',
    craftStyle: 'Awadhi Needlecraft Embroidery',
    region: 'Lucknow, Uttar Pradesh',
    materials: 'Fine Mulmul Cotton, Organic Cotton Thread, Natural Pearl Wash',
    price: 2800,
    availableQuantity: 6,
    priceRange: {
      min: 2500,
      max: 3400,
      reasoning: 'Took 18 days of micro-needle hand embroidery by women artisan collectives in Old Lucknow.',
    },
    images: [
      '/crafts/chikankari-dupatta.jpg',
    ],
    story: 'Patronized by the Nawabs of Awadh and Queen Noor Jahan, celebrating the delicate artistry of white-on-white embroidery.',
    culturalNote: 'Shadow-work creates an opaque embossed effect on the front by stitching criss-cross threads on the reverse.',
    tags: ['Chikankari', 'Lucknow', 'Embroidery', 'CottonDupatta'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 8. Kashmir Walnut Wood Chest
  {
    id: 'curated-kashmir-walnut',
    artisanId: 'artisan-ghulam-nabi',
    artisanName: 'Ghulam Nabi Mir',
    productName: 'Kashmir Hand-Carved Walnut Wood Chest',
    description: 'Sculpted from seasoned 150-year-old root walnut timber, seasoned for years and hand-carved with open lattice Chinar foliage.',
    craftType: 'Woodwork',
    craftStyle: 'Deep Relief Intaglio Carving',
    region: 'Srinagar, Kashmir',
    materials: 'Solid Wild Walnut Wood (Doon Kaath), Natural Agate Stone Polish, Velvet Lining',
    price: 7200,
    availableQuantity: 5,
    priceRange: {
      min: 6800,
      max: 8500,
      reasoning: 'Carved using precision steel chisels from solid seasoned root wood with zero artificial varnish.',
    },
    images: [
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1080&q=80',
    ],
    story: 'Handcrafted in old Srinagar by master woodcarvers using native walnut logs seasoned over 4 winters.',
    culturalNote: 'The wax polish is buffed using smooth river agate stones to bring out the natural grain luster.',
    tags: ['KashmirWalnut', 'WoodCarving', 'ArtisanalHome', 'HeritageCraft'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },

  // 9. Channapatna Wooden Toys
  {
    id: 'curated-channapatna-lacquer',
    artisanId: 'artisan-syed-khaleel',
    artisanName: 'Syed Khaleel',
    productName: 'Channapatna Organic Wood Balancing Toys',
    description: 'Eco-friendly traditional turned wooden toys colored with non-toxic turmeric, indigo, and kumkum dyes sealed with natural lac resin.',
    craftType: 'Woodwork',
    craftStyle: 'Lathe-Turned Natural Lacquerware',
    region: 'Channapatna, Karnataka',
    materials: 'Wrightia Tinctoria (Ivory Wood), Natural Shellac, Turmeric & Spinach Dyes',
    price: 1650,
    availableQuantity: 8,
    priceRange: {
      min: 1500,
      max: 2100,
      reasoning: 'Child-safe 100% organic herbal pigments applied on high-speed lathe with screw-pine leaf finishing.',
    },
    images: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=1080&q=80',
    ],
    story: 'Originating in the 18th century under Tipu Sultan, practiced by generational lathe artisans of the "Gombegala Ooru" (Toy Town).',
    culturalNote: 'Finished by polishing with wild screw-pine leaves while turning on the lathe.',
    tags: ['ChannapatnaToys', 'GIProtected', 'NaturalLacquer', 'EcoCraft'],
    status: 'Published',
    createdAt: '2025-01-01T00:00:00.000Z',
    updatedAt: '2025-01-01T00:00:00.000Z',
  },
];
