import { Product } from './types';

export const CURATED_HERITAGE_PRODUCTS: Product[] = [
  {
    id: 'curated-jaipur-pottery',
    artisanId: 'artisan-ramesh-kumar',
    artisanName: 'Ramesh Kumar Kumhar',
    productName: 'Jaipur Turquoise Blue Pottery Floral Urn',
    description: 'Authentic GI-tagged Jaipur Blue Pottery handcrafted using quartz stone powder, raw glass, and natural cobalt oxide pigments without conventional clay.',
    craftType: 'Pottery',
    craftStyle: 'Mughal & Persian Floral Glaze',
    region: 'Jaipur, Rajasthan',
    materials: 'Quartz Stone, Multani Mitti, Natural Copper Oxide, Raw Glass Glaze',
    price: 3450,
    availableQuantity: 4,
    priceRange: {
      min: 3200,
      max: 4000,
      reasoning: 'Intricate 14-day double-firing process and hand-painted Persian cobalt motifs.',
    },
    images: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=1080&q=80',
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1080&q=80',
    ],
    story: 'Carrying forward a 5-generation legacy of palace potters from the royal ateliers of Maharaja Sawai Ram Singh II.',
    culturalNote: 'One of the few pottery crafts globally that uses no clay, producing a glassy turquoise resonance.',
    tags: ['BluePottery', 'JaipurCraft', 'FairTrade', 'HandmadeIndia'],
    status: 'Published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'curated-banarasi-zari',
    artisanId: 'artisan-munna-ansari',
    artisanName: 'Munna Lal Ansari',
    productName: 'Kashi Royal Crimson Katan Silk Brocade Saree',
    description: 'Master handloom woven Katan silk saree adorned with gold-plated silver Zari kadwa floral jaal, requiring over 280 hours of handloom precision.',
    craftType: 'Textiles',
    craftStyle: 'Kadwa Handloom Brocade',
    region: 'Varanasi, Uttar Pradesh',
    materials: 'Pure Mulberry Silk, 24K Electroplated Silver Zari, Natural Lac Dye',
    price: 18500,
    availableQuantity: 2,
    priceRange: {
      min: 17000,
      max: 22000,
      reasoning: 'Extensive handloom kadwa weaving technique with certified real silver metallic zari threads.',
    },
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1080&q=80',
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=1080&q=80',
    ],
    story: 'Woven on a traditional wooden pit loom along the ghats of Varanasi by the master weaving family of Ansari.',
    culturalNote: 'Each floral motif is woven individually without loose floats on the reverse side.',
    tags: ['BanarasiSilk', 'Handloom', 'VaranasiCraft', 'ZariHeritage'],
    status: 'Published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'curated-dhokra-brass',
    artisanId: 'artisan-sukhranjan-baghel',
    artisanName: 'Sukhranjan Baghel',
    productName: 'Bastar Tribal Dhokra Lost-Wax Dancing Deer Figurine',
    description: '4,000-year-old non-ferrous bell metal casting technique using beeswax threads and alluvial clay molds from the riverbanks of Bastar.',
    craftType: 'Metalwork',
    craftStyle: 'Bastar Lost-Wax Cast Metal',
    region: 'Bastar, Chhattisgarh',
    materials: 'Pure Bell Metal Brass, Natural Beeswax, Damar Resin, River Clay',
    price: 4800,
    availableQuantity: 3,
    priceRange: {
      min: 4500,
      max: 5600,
      reasoning: 'Single-mold lost-wax process where every piece is an irreproducible one-of-a-kind original.',
    },
    images: [
      'https://images.unsplash.com/photo-1582562124811-c09040d0a901?auto=format&fit=crop&w=1080&q=80',
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1080&q=80',
    ],
    story: 'Preserved by the tribal metalsmiths of Bastar, dating back directly to the Dancing Girl artifact of Mohenjo-Daro.',
    culturalNote: 'Because the wax mold is destroyed during molten pouring, no two Dhokra statues can ever be identical.',
    tags: ['DhokraArt', 'LostWaxCasting', 'TribalHeritage', 'BastarBrass'],
    status: 'Published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'curated-kashmir-walnut',
    artisanId: 'artisan-ghulam-nabi',
    artisanName: 'Ghulam Nabi Mir',
    productName: 'Kashmir Hand-Carved Walnut Wood Chinar Motif Jewelry Chest',
    description: 'Sculpted from seasoned 150-year-old root walnut timber, seasoned for years and hand-carved with open lattice Chinar foliage.',
    craftType: 'Woodwork',
    craftStyle: 'Deep Relief Intaglio Carving',
    region: 'Srinagar, Kashmir',
    materials: 'Solid Wild Walnut Wood (Doon Kaath), Natural Agate Stone Polish, Velvet Lining',
    price: 7200,
    availableQuantity: 5,
    priceRange: {
      min: 6800,
      max: 8500,
      reasoning: 'Carved using precision steel chisels from solid seasoned root wood with zero artificial varnish.',
    },
    images: [
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1080&q=80',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1080&q=80',
    ],
    story: 'Handcrafted in old Srinagar by master woodcarvers using native walnut logs seasoned over 4 winters.',
    culturalNote: 'The wax polish is buffed using smooth river agate stones to bring out the natural grain luster.',
    tags: ['KashmirWalnut', 'WoodCarving', 'ArtisanalHome', 'HeritageCraft'],
    status: 'Published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'curated-channapatna-lacquer',
    artisanId: 'artisan-syed-khaleel',
    artisanName: 'Syed Khaleel',
    productName: 'Channapatna Organic Ivory Wood Balancing Toys Set',
    description: 'Eco-friendly traditional turned wooden toys colored with non-toxic turmeric, indigo, and kumkum dyes sealed with natural lac resin.',
    craftType: 'Woodwork',
    craftStyle: 'Lathe-Turned Natural Lacquerware',
    region: 'Channapatna, Karnataka',
    materials: 'Wrightia Tinctoria (Ivory Wood), Natural Shellac, Turmeric & Spinach Dyes',
    price: 1650,
    availableQuantity: 8,
    priceRange: {
      min: 1500,
      max: 2100,
      reasoning: 'Child-safe 100% organic herbal pigments applied on high-speed lathe with screw-pine leaf finishing.',
    },
    images: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=1080&q=80',
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=1080&q=80',
    ],
    story: 'Originating in the 18th century under Tipu Sultan, practiced by generational lathe artisans of the "Gombegala Ooru" (Toy Town).',
    culturalNote: 'Finished by polishing with wild screw-pine leaves while turning on the lathe.',
    tags: ['ChannapatnaToys', 'GIProtected', 'NaturalLacquer', 'EcoCraft'],
    status: 'Published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
